"""empty message

Revision ID: 8536246c5705
Revises: 
Create Date: 2020-07-22 13:32:36.779660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8536246c5705'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('summaries_sources', sa.LargeBinary(), nullable=True),
    sa.Column('summaries_multiplier', sa.Integer(), nullable=True),
    sa.Column('summaries_sectors', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_summaries_multiplier'), 'user', ['summaries_multiplier'], unique=False)
    op.create_index(op.f('ix_user_summaries_sectors'), 'user', ['summaries_sectors'], unique=False)
    op.create_index(op.f('ix_user_summaries_sources'), 'user', ['summaries_sources'], unique=False)
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_company_name'), 'dashboard', ['company_name'], unique=False)
    op.create_index(op.f('ix_dashboard_display_name'), 'dashboard', ['display_name'], unique=False)
    op.create_index(op.f('ix_dashboard_timestamp'), 'dashboard', ['timestamp'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_description'), 'group', ['description'], unique=False)
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=False)
    op.create_index(op.f('ix_group_timestamp'), 'group', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_timestamp'), table_name='group')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_index(op.f('ix_group_description'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_dashboard_timestamp'), table_name='dashboard')
    op.drop_index(op.f('ix_dashboard_display_name'), table_name='dashboard')
    op.drop_index(op.f('ix_dashboard_company_name'), table_name='dashboard')
    op.drop_table('dashboard')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_index(op.f('ix_user_summaries_sources'), table_name='user')
    op.drop_index(op.f('ix_user_summaries_sectors'), table_name='user')
    op.drop_index(op.f('ix_user_summaries_multiplier'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
