"""empty message

Revision ID: cfa13d9934cf
Revises: 8536246c5705
Create Date: 2020-07-22 14:29:16.828705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa13d9934cf'
down_revision = '8536246c5705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('companies', sa.LargeBinary(), nullable=True))
    op.create_index(op.f('ix_group_companies'), 'group', ['companies'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_companies'), table_name='group')
    op.drop_column('group', 'companies')
    # ### end Alembic commands ###
